version: '3'
services:
  redis-cluster:
    image: redis:latest
    networks:
      redis-net:
        ipv4_address: 172.20.0.2
    command: redis-cli --cluster create 172.20.0.3:7000 172.20.0.4:7001 172.20.0.5:7002 172.20.0.6:7003 172.20.0.7:7004 172.20.0.8:7005 --cluster-replicas 1  --cluster-yes
    depends_on:
      - redis1
      - redis2
      - redis3
      - redis4
      - redis5
      - redis6
  redis1:
    image: redis:latest
    container_name: redis1
    restart: always
    networks:
      redis-net:
        ipv4_address: 172.20.0.3
    ports:
      - 7000:7000
      - 17000:17000
    volumes:
      - ./7000/conf/redis.conf:/etc/redis/redis.conf
      - ./7000/data:/data
    command: redis-server /etc/redis/redis.conf

  redis2:
    image: redis:latest
    container_name: redis2
    restart: always
    networks:
      redis-net:
        ipv4_address: 172.20.0.4
    ports:
      - 7001:7001
      - 17001:17001
    volumes:
      - ./redis1_data/7001/conf/redis.conf:/etc/redis/redis.conf
      - ./7001/data:/data
    command: redis-server /etc/redis/redis.conf

  redis3:
    image: redis:latest
    container_name: redis3
    restart: always
    networks:
      redis-net:
        ipv4_address: 172.20.0.5
    ports:
      - 7002:7002
      - 17002:17002
    volumes:
      - ./7002/conf/redis.conf:/etc/redis/redis.conf
      - ./7002/data:/data
    command: redis-server /etc/redis/redis.conf
  redis4:
    image: redis:latest
    container_name: redis4
    restart: always
    networks:
      redis-net:
        ipv4_address: 172.20.0.6
    ports:
      - 7003:7003
      - 17003:17003
    volumes:
      - ./7003/conf/redis.conf:/etc/redis/redis.conf
      - ./7003/data:/data
    command: redis-server /etc/redis/redis.conf
  redis5:
    image: redis:latest
    container_name: redis5
    restart: always
    networks:
      redis-net:
        ipv4_address: 172.20.0.7
    ports:
      - 7004:7004
      - 17004:17004
    volumes:
      - ./7004/conf/redis.conf:/etc/redis/redis.conf
      - ./7004/data:/data
    command: redis-server /etc/redis/redis.conf
  redis6:
    image: redis:latest
    container_name: redis6
    restart: always
    networks:
      redis-net:
        ipv4_address: 172.20.0.8
    ports:
      - 7005:7005
      - 17005:17005
    volumes:
      - ./7005/conf/redis.conf:/etc/redis/redis.conf
      - ./7005/data:/data
    command: redis-server /etc/redis/redis.conf
    
networks:
  redis-net:
     driver: bridge
     ipam:
       driver: default
       config:
          -
           subnet: 172.20.0.0/16

#volumes:
  #redis1_data:
  #redis2_data:
  #redis3_data:
  #redis4_data:
  #redis5_data:
  #redis6_data: